# ADN Greenpeace Client

FROM node:14 as adn_greenpeace_app
WORKDIR /usr/src/app
COPY . /usr/src/app/

RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent 
RUN npm run types
RUN npm run build 

FROM nginx:1.16.0-alpine
COPY --from=adn_greenpeace_app /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80 
CMD ["nginx","-g","daemon off;"]