# ADN Greenpeace Client

FROM node:14
WORKDIR /usr/src/app
ENV PATH /app/node_modules/.bin:$PATH
# COPY package.json ./
# COPY package-*.json yarn.lock ./
# COPY .npmrc ./
COPY . ./
# COPY . ./
RUN npm install react-scripts -g
# RUN yarn
RUN npm install
RUN npm run types
# CMD ["npm", "run", "client:start"]
EXPOSE 3000
