# ADN Greenpeace Client

FROM node:14 as adn_greenpeace_app
WORKDIR /usr/app/build

# COPY . /usr/app/
# RUN npm install
# RUN npm install react-scripts -g
# RUN npm run types
# RUN npm run client:build 

COPY ./build /usr/app/build

FROM nginx:1.16.0-alpine

COPY --from=adn_greenpeace_app /usr/app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80 
CMD ["nginx","-g","daemon off;"]

