# ADN Greenpeace Client

FROM node:14
WORKDIR /usr/src/app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-*.json yarn.lock ./
COPY .npmrc ./
RUN yarn
COPY . ./
RUN npm run types
RUN npm run client:start
EXPOSE 3000
