# ADN Greenpeace Client Production

FROM node:14 as adn_greenpeace_app
WORKDIR /usr/app/build

COPY . /usr/app/
RUN npm install -g typescript
RUN npm install -g react-scripts
RUN npm install
RUN npm run types
RUN cp /usr/app/.htaccess /usr/app/public/.htaccess
RUN cp /usr/app/.env.production.sample /usr/app/.env.production
RUN npm run client:build:production

FROM nginx:1.16.0-alpine
COPY --from=adn_greenpeace_app /usr/app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80 
CMD ["nginx","-g","daemon off;"]
